### ISSUE TITLE
newtab: homepage vs newtab page

### ISSUE THREAD

**Issue by Bugs1234** [lbarchive/KLTT#3]
Hello,
I would like the option to have the added tab be the newtab page instead of the homepage.
You can test this out by going to Settings - Appearance. Tick 'Show Home Button' and then you have the option of 'Change'. Under 'Change' you can choose 'Use the New Tab page' or 'open this page...'. If you choose 'open this page...' you can enter any page you want instead of newtab page.
Then test your extension. It will open the page you chose there instead of new tab page. But if I just click the button to open a new tab, I get the regular newtab page.
This would be nice to be an option in your extension, to have the option to open regular newtab page instead of homepage.
Thank you.

**Comment by livibetter** [comment]
I just published v0.5 with new option to specify a custom page, please upgrade to see if it does what you want.

**Comment by Bugs1234** [comment]
yes, that was a very fast implementation and it works perfectly.
thank you very much!
