### ISSUE TITLE
doesn't seem to work with gmail offline

### ISSUE THREAD

**Issue by markifi** [lbarchive/KLTT#4]
hello, and thank you for this great extension. i think it's really useful.

how to reproduce:
install chrome  22.0.1229.94, windows 7 x64, KLTT and gmail offline 
close all tabs, open new window
you will see one tab open

not a big issue, but i thought it's better be documented.

about gmail offline:
https://chrome.google.com/webstore/detail/gmail-offline/ejidjjhkpiempkbhmpbfngldlkglhimk
this extension keeps chrome alive after closing every tab, in order to be able to fetch gmail emails while in background, it minimizes chrome to tray.

**Comment by livibetter** [comment]
Thanks for reporting. I am not actually using Chrome and not up to check and fix.

If anyone can confirm this, please comment. If you can fix it, please open pull request, I will push update to Chrome store.
